name: Delete AWS Infrastructure

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Delete CloudFormation Stack
      run: |
        aws cloudformation delete-stack --stack-name proyecto-aws-stack
        aws cloudformation wait stack-delete-complete --stack-name proyecto-aws-stack