name: Delete Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm_delete:
        description: 'Type "DELETE" to confirm infrastructure deletion'
        required: true
        type: string

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Wait for manual approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: chris-jt # Reemplazar esto con tu nombre de usuario de GitHub

    - name: Delete CloudFormation stack
      run: |
        aws cloudformation delete-stack --stack-name my-stack