name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm_deploy:
        description: 'Type "DEPLOY" to confirm infrastructure deployment'
        required: true
        type: string


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Asegúrate de que esta sea la región correcta

    - name: Deploy to AWS CloudFormation
      run: |
        aws cloudformation deploy \
          --template-file cloudformation/template.yml \
          --stack-name my-stack \
          --parameter-overrides AccountId=${{ secrets.AWS_ACCOUNT_ID }} \
          --capabilities CAPABILITY_IAM

    - name: Wait for CloudFormation stack to complete
      run: |
        aws cloudformation wait stack-create-complete --stack-name my-stack

    - name: Debug - List Stack Outputs
      run: |
        aws cloudformation describe-stacks --stack-name my-stack --query "Stacks[0].Outputs"

    - name: Get S3 bucket name
      run: |
        BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name my-stack --query "Stacks[0].Outputs[?OutputKey=='WebsiteBucketName'].OutputValue" --output text)
        echo "Bucket Name: $BUCKET_NAME"
        echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

    - name: Debug - Print Bucket Name
      run: |
        echo "Bucket Name from env: ${{ env.BUCKET_NAME }}"

    - name: Upload website to S3
      run: |
        if [ -z "${{ env.BUCKET_NAME }}" ]; then
          echo "Error: Bucket name is empty"
          exit 1
        fi
        aws s3 cp web/index.php s3://${{ env.BUCKET_NAME }}/