name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm_deploy:
        description: 'Type "DEPLOY" to confirm infrastructure deployment'
        required: true
        type: string


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Asegurar de que esta sea la región correcta

    - name: Create temporary S3 bucket
      run: |
          TEMP_BUCKET_NAME="temp-bucket-${{ github.run_id }}"
          aws s3 mb s3://$TEMP_BUCKET_NAME
          echo "TEMP_BUCKET_NAME=$TEMP_BUCKET_NAME" >> $GITHUB_ENV

    - name: Upload files to temporary S3 bucket
      run: |
          aws s3 cp ../scripts/install_apache.sh s3://${{ env.TEMP_BUCKET_NAME }}/
          aws s3 cp ../scripts/mount_s3.sh s3://${{ env.TEMP_BUCKET_NAME }}/
          aws s3 cp ../web/index.php s3://${{ env.TEMP_BUCKET_NAME }}/    
      working-directory: cloudformation

    - name: List directory contents
      run: |
        echo "Current directory:"
        ls -la
        echo "Cloudformation directory (if exists):"
        ls -la cloudformation || echo "Cloudformation directory does not exist"
    
    - name: Deploy to AWS CloudFormation
      run: |
        aws cloudformation deploy \
          --template-file cloudformation/template.yml \
          --stack-name PIN-stack \
          --parameter-overrides AccountId=${{ secrets.AWS_ACCOUNT_ID }} TempBucketName=${{ env.TEMP_BUCKET_NAME }} \
          --capabilities CAPABILITY_IAM
      #working-directory: cloudformation

    - name: Wait for CloudFormation stack to complete
      run: |
        aws cloudformation wait stack-create-complete --stack-name PIN-stack

    - name: Debug - List Stack Outputs
      run: |
        aws cloudformation describe-stacks --stack-name PIN-stack --query "Stacks[0].Outputs"

    - name: Get S3 bucket name
      run: |
        BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name PIN-stack --query "Stacks[0].Outputs[?OutputKey=='WebsiteBucketName'].OutputValue" --output text)
        echo "Bucket Name: $BUCKET_NAME"
        echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

    - name: Copy files from temporary bucket to final bucket
      run: |
          aws s3 sync s3://${{ env.TEMP_BUCKET_NAME }} s3://${{ env.BUCKET_NAME }}

    - name: Delete temporary S3 bucket
      run: |
          aws s3 rb s3://${{ env.TEMP_BUCKET_NAME }} --force
    
    - name: Debug - Print Bucket Name
      run: |
        echo "Bucket Name from env: ${{ env.BUCKET_NAME }}"
