name: Deploy Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to AWS CloudFormation
      run: |
        aws cloudformation deploy \
          --template-file cloudformation/template.yml \
          --stack-name my-stack \
          --parameter-overrides AccountId=${{ secrets.AWS_ACCOUNT_ID }} \
          --capabilities CAPABILITY_IAM \
          --no-execute-changeset

    - name: Wait for manual approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: your-github-username

    - name: Execute CloudFormation changeset
      run: |
        aws cloudformation execute-change-set \
          --stack-name my-stack \
          --change-set-name $(aws cloudformation list-change-sets --stack-name my-stack --query 'Summaries[0].ChangeSetName' --output text)

    - name: Upload website to S3
      run: |
        aws s3 cp web/index.php s3://my-website-bucket-${{ secrets.AWS_ACCOUNT_ID }}/