name: Deploy Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Asegúrate de que esta sea la región correcta

    - name: Deploy to AWS CloudFormation
      run: |
        aws cloudformation deploy \
          --template-file cloudformation/template.yml \
          --stack-name my-stack \
          --parameter-overrides AccountId=${{ secrets.AWS_ACCOUNT_ID }} \
          --capabilities CAPABILITY_IAM \
          --no-execute-changeset

    - name: Wait for manual approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.GITHUB_TOKEN }}
        approvers: chris-jt  # este es tu nombre de usuario de GitHub

    - name: Execute CloudFormation changeset
      run: |
        aws cloudformation execute-change-set \
          --stack-name my-stack \
          --change-set-name $(aws cloudformation list-change-sets --stack-name my-stack --query 'Summaries[0].ChangeSetName' --output text)

    - name: Wait for CloudFormation stack to complete
      run: |
        aws cloudformation wait stack-create-complete --stack-name my-stack

    - name: Get S3 bucket name
      run: |
        BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name my-stack --query "Stacks[0].Outputs[?OutputKey=='WebsiteBucketName'].OutputValue" --output text)
        echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

    - name: Upload website to S3
      run: |
        aws s3 cp web/index.php s3://${{ env.BUCKET_NAME }}/