name: Deploy to AWS

on:
    workflow_dispatch:
      inputs:
        confirm_deploy:
          description: 'Type "DEPLOY" to confirm infrastructure deployment'
          required: true
          type: string
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to AWS CloudFormation
      run: |
        aws cloudformation deploy \
          --template-file terraform/template.yaml \
          --stack-name proyecto-aws-stack \
          --parameter-overrides KeyName=${{ secrets.EC2_KEY_NAME }} \
          --capabilities CAPABILITY_NAMED_IAM